### ISSUE TITLE
Issue found with `bind_rows()` when updating main data in `while` loop 

### ISSUE THREAD

**Issue by bcaneco** [dmpstats/Avian_Cluster_Detection#10]
While testing with a random dataset:
 - study: Savannah-MEFT, 
 - animal IDs: "SAV-4360-A", "SAV-4384-A", "SAV-4355-B", "SAV-4356-A",  "SAV-4386-A", "SAV-4357-A", "SAV-4358-A")
 - "2024-02-14 UTC" - "2024-03-15 UTC"

The app crashed, returning the following error:
`Error: All individuals in the move object should be in the associated track data.`

Debugging showed the offending code is the `bind_rows` step in the following pipe:

https://github.com/dmpstats/Avian_Cluster_Detection/blob/572e00fbd0e2d8761f6ee6cabf4dd1b974ad04ca/RFunction.R#L524-L529

The error should be solved via `mt_stack()`. **However**, this won't be possible until recent changes to the merging strategy (as discussed in https://gitlab.com/bartk/move2/-/issues/72) are included in a future CRAN released of `{move2}`.

So, we'll have to sit on this one for now.

**Comment by lindesaysh** [comment]
`mt_stack` line of code should work now so we need to switch over to this.  The latest vulture tags throw an error owing to the limited data currently available for these.  Same error as we got for the Savannah tags about individuals. 

the bind_rows doesnt work when the filtered `data` object does not contain all the track ids that are in the `xydata` object.  

I have run it locally using line 528 instead of line 527 and it works fine.  I'll let you do the update to the live version @bcaneco so i don't make a mess 😆

**Comment by bcaneco** [comment]
New version released with fix to this issue by replacement of `bind_rows()` with `mt_stack()`. No errors found when re-running the App for example dataset reported above.

Having passed unit and sdk testing locally, and trialled online in MoveApps for a couple of WFs, the updated App version is now available to all on MoveApps.

Closing this issue as a result.
